"""init_aaos_schema

Revision ID: 8245fc50ff27
Revises: 
Create Date: 2025-11-25 12:36:46.819258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8245fc50ff27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_communications',
    sa.Column('comm_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('comm_id')
    )
    with op.batch_alter_table('agent_communications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_communications_comm_id'), ['comm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_communications_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_communications_sender_id'), ['sender_id'], unique=False)

    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_agent_id'), ['agent_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_log_id'), ['log_id'], unique=False)

    op.create_table('consciousness_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.Column('awareness_level', sa.Integer(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('consciousness_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consciousness_snapshots_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consciousness_snapshots_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('reasoning_chains',
    sa.Column('chain_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('reasoning_type', sa.String(length=50), nullable=False),
    sa.Column('steps_json', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id')
    )
    with op.batch_alter_table('reasoning_chains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reasoning_chains_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reasoning_chains_chain_id'), ['chain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reasoning_chains_task_id'), ['task_id'], unique=False)

    op.create_table('system_metrics',
    sa.Column('metric_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.String(length=255), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('metric_id')
    )
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_metrics_metric_id'), ['metric_id'], unique=False)

    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_task_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_metrics_metric_id'))

    op.drop_table('system_metrics')
    with op.batch_alter_table('reasoning_chains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reasoning_chains_task_id'))
        batch_op.drop_index(batch_op.f('ix_reasoning_chains_chain_id'))
        batch_op.drop_index(batch_op.f('ix_reasoning_chains_agent_id'))

    op.drop_table('reasoning_chains')
    with op.batch_alter_table('consciousness_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consciousness_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_consciousness_snapshots_agent_id'))

    op.drop_table('consciousness_snapshots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_log_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_agent_id'))

    op.drop_table('agents')
    with op.batch_alter_table('agent_communications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_communications_sender_id'))
        batch_op.drop_index(batch_op.f('ix_agent_communications_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_agent_communications_comm_id'))

    op.drop_table('agent_communications')
    # ### end Alembic commands ###
